blank_issues_enabled: true
contact_links:
    - name: Felix Hoffmann
      url: 'mailto:felix.emmanuel.hoffmann@gmail.com'
      about: Hi there! I'm Felix. Feel free to contact me if you have any questions or suggestions.
    - name: Leopold Fuchs
      url: 'mailto:kontakt@leopold-fuchs.de'
      about: Hi, I'm Leopold. Feel free to contact me.
