name: 💡 Feature Request
title: "💡 [feat] <Title>"
description: Request a new feature
labels: ["feature"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A simple description for what is currently missing or needs to be improved.
    validations:
      required: true

  - type: textarea
    id: in-scope
    attributes:
      label: 🟢 In Scope
      description: Please list all tasks required or related to your requested feature.
      placeholder: "- [] Lorem Ipsum"
    validations:
      required: true

  - type: textarea
    id: not-in-scope
    attributes:
      label: 🔴 Not in Scope
      description: What tasks are to large or not related to your requested feature.
      placeholder: "- _None_"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
